# Generated by Django 4.2.10 on 2024-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
